_wandb:
    value:
        cli_version: 0.26.1
        e:
            hf0y52kwqi48dhvklr74jdt8m4k3un8a:
                args:
                    - --mode
                    - best
                    - --k1
                    - "1.2"
                    - --b
                    - "0.75"
                codePath: src/run_bm25.py
                codePathLocal: src/run_bm25.py
                email: ilayda@ergur.net
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/ai/bin/python
                git:
                    commit: 938f7dec85cbff85ef455f9c09076b4bfb16353d
                    remote: https://github.com/ilaydaergur/IS584_Project.git
                host: Mac.home
                os: macOS-26.4.1-arm64-arm-64bit
                program: /Users/ilaydaergur/Desktop/METU/IS584/IS584_Project/src/run_bm25.py
                python: CPython 3.11.15
                root: /Users/ilaydaergur/Desktop/METU/IS584/IS584_Project
                startedAt: "2026-05-09T22:37:48.379962Z"
                writerId: hf0y52kwqi48dhvklr74jdt8m4k3un8a
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.15
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
b:
    value: 0.75
k1:
    value: 1.2
model:
    value: BM25
